apiVersion: v1
kind: Pod
metadata:
  name: mydb
  labels:
    app: mydb
spec:
  containers:
  - name: mydb
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: rootpass
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: userpass
    - name: MYSQL_DATABASE
      value: testdb