apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrssetbased
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
    matchExpressions:
      - key: team
        operator: In
        values:
          - "team1"
      - key: tier
        operator: In
        values:
          - "frontend"
  template:
    metadata:
      name: rssetpod
      labels:
        env: prod
        team: team1
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.16