apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: wpod
      labels:
        env: prod
    spec:
      volumes:
        - name: mypd-pvc
          persistentVolumeClaim:
           claimName: mypvc
           
      containers:
      - name: nginx
        image: nginx:1.16
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: mypd-pvc
